### PR TITLE
ocrd-tool.json: register SavedModel resources

### PR DESCRIPTION
**Pull request by bertsky**
This is how decentralized resource locations would look like now. I have used @apacha's release URLs for now. (Notice there is a deviation in how the 2021-03-09 archive is substructured. Also, the MacOS directories may get in the way.)

### CODE REVIEW

**Review by kba — APPROVED** [review]

**Review by vahidrezanezhad — APPROVED** [review]

**Comment by bertsky** [comment]
@apacha we still have not uploaded the converted models to [qurator-data.de](https://qurator-data.de/sbb_binarization/2021-03-09/), and the [Huggingface model repo](https://huggingface.co/SBB/sbb_binarization/tree/main/saved_model/2021_03_09) [does not support producing archives](https://github.com/huggingface/huggingface_hub/issues/737) (only URLs for single file names or programmatic downloads via `huggingface_hub.snapshot_download`), so currently the [release archive](https://github.com/apacha/sbb_binarization/releases/download/pre-trained-models/model_2021_03_09.zip) on your fork is the only resource we can use within ocrd resmgr.

Could you please remove the subdirectories `__MACOSX` and `model_2021_03_09/.DS_Store` from the zip file and re-release?

Otherwise, @vahidrezanezhad can we add the fixed zip file to a new release here on the main repo? (Would be as simply as [`gh release -R qurator-spk/sbb_binarization upload v0.0.11 default-2021-03-09.zip`](https://cli.github.com/manual/gh_release_upload) ...)

**Comment by cneud** [comment]
Sorry for the delays! If it is of immediate help for OCR-D I can add the cleaned Saved Models here to the release.

**Comment by bertsky** [comment]
> If it is of immediate help for OCR-D I can add the cleaned Saved Models here to the release.

Yes, that would really help! (In the current state, the model does not resolve after downloading because of the macos directories getting in the way...)

**Comment by cneud** [comment]
Now added here https://github.com/qurator-spk/sbb_binarization/releases/download/v0.0.11/saved_model_2021_03_09.zip

**Comment by cneud** [comment]
For consistency, I now also added a clean version of https://github.com/qurator-spk/sbb_binarization/releases/download/v0.0.11/saved_model_2020_01_16.zip

**Comment by apacha** [comment]
@bertsky I tried to clean the archives and tried to remove the `.DS_Store` files and `__MACOSX` subdirectories. The new versions are uploaded to https://github.com/apacha/sbb_binarization/releases/tag/pre-trained-models. Not sure if it still is necessary though, now that you have them stored in the upstream repo.

BTW: I'm happy that my [proposed approach](https://github.com/qurator-spk/sbb_binarization/pull/44) of storing the models in a github release finally made it ;-).

**Pull request merged**
